// SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and Gardener contributors
//
// SPDX-License-Identifier: Apache-2.0

package constants

const (
	// OperatorName is the name of the scalingadvisor operator.
	OperatorName = "scalingadvisor"
	// OperatorConfigGroupName is the group name for OperatorConfiguration
	OperatorConfigGroupName = "config.sa.gardener.cloud"
	// OperatorGroupName is the name of the group for all scaling recommender custom resources.
	OperatorGroupName = "sa.gardener.cloud"
)

const (
	// KindScalingAdvisorConfiguration is the KIND for scaling advisor configuration.
	KindScalingAdvisorConfiguration = "ScalingAdvisorConfiguration"
	// KindClusterScalingAdvice is the KIND for ClusterScalingAdvice generated by the scaling-advisor operator.
	KindClusterScalingAdvice = "ClusterScalingAdvice"
	// KindClusterScalingConstraint is the KIND for constraint object that is reconciled by the scaling-advisor operator in order to generate the scaling advice.
	KindClusterScalingConstraint = "ClusterScalingConstraint"
)

const (
	// AnnotationEnableScalingDiagnostics is the annotation key to enable scaling diagnostics for a cluster.
	// This is applied by a user/tool on the ClusterScalingConstraint object which produces diagnostics within
	// the generated ClusterScalingAdvice.Status.
	AnnotationEnableScalingDiagnostics = "sa.gardener.cloud/enable-scaling-diagnostics"
)

const (
	// LabelSimulationName is the label key to identify name of the simulation inside a simulation group.
	LabelSimulationName = "sa.gardener.cloud/simulation-name"
	// LabelSimulationGroupPassNum is the label key to identify the pass number of the simulation group.
	LabelSimulationGroupPassNum = "sa.gardener.cloud/simulation-group-pass-num"
	// LabelNodePoolName is the label key to identify the node pool name for which the simulation is being run.
	LabelNodePoolName = "sa.gardener.cloud/node-pool-name"
	// LabelNodeTemplateName is the label key to identify the node template name for which the simulation is being run.
	LabelNodeTemplateName = "sa.gardener.cloud/node-template-name"
	// LabelRequestID is the label key to identify the request Name of scaling advice request.
	LabelRequestID = "sa.gardener.cloud/request-id"
	// LabelCorrelationID is the label key to identify the correlation Name of the scaling advice request.
	LabelCorrelationID = "sa.gardener.cloud/correlation-id"
)

const (
	// DefaultOperatorServerPort is the default port for the scaling advisor operator server.
	DefaultOperatorServerPort = 8080
	// DefaultOperatorHealthProbePort is the default port for the operator health probe endpoints.
	DefaultOperatorHealthProbePort = 8081
	// DefaultOperatorMetricsPort is the default port for the operator metrics endpoint.
	DefaultOperatorMetricsPort = 8082
	// DefaultOperatorProfilingPort is the default port for the operator profiling endpoints.
	DefaultOperatorProfilingPort = 8083
	// DefaultAdvisorServicePort is the default port for the scaling advisor service.
	DefaultAdvisorServicePort = 8090
	// DefaultMinKAPIPort is the default port for the MinKAPI service.
	DefaultMinKAPIPort = 8091
)
