// SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and Gardener contributors
//
// SPDX-License-Identifier: Apache-2.0

package constants

import (
	"net"
	"strconv"
)

const (
	// OperatorName is the name of the scalingadvisor operator.
	OperatorName = "scalingadvisor"
	// OperatorConfigGroupName is the group name for OperatorConfiguration
	OperatorConfigGroupName = "config.sa.gardener.cloud"
	// OperatorGroupName is the name of the group for all scaling recommender custom resources.
	OperatorGroupName = "sa.gardener.cloud"
)

const (
	// KindScalingAdvisorConfiguration is the KIND for scaling advisor configuration.
	KindScalingAdvisorConfiguration = "ScalingAdvisorConfiguration"
	// KindClusterScalingAdvice is the KIND for ClusterScalingAdvice generated by the scaling-advisor operator.
	KindClusterScalingAdvice = "ClusterScalingAdvice"
	// KindClusterScalingConstraint is the KIND for constraint object that is reconciled by the scaling-advisor operator in order to generate the scaling advice.
	KindClusterScalingConstraint = "ClusterScalingConstraint"
)

const (
	// AnnotationEnableScalingDiagnostics is the annotation key to enable scaling diagnostics for a cluster.
	// This is applied by a user/tool on the ClusterScalingConstraint object which produces diagnostics within
	// the generated ClusterScalingAdvice.Status.
	AnnotationEnableScalingDiagnostics = "sa.gardener.cloud/enable-scaling-diagnostics"
)

const (
	// LabelSimulationName is the label key to identify name of the simulation inside a simulation group.
	LabelSimulationName = "sa.gardener.cloud/simulation-name"
	// LabelSimulationGroupName is the label key to identify the name of the simulation group.
	LabelSimulationGroupName = "sa.gardener.cloud/simulation-group-name"
	// LabelSimulationGroupNumPasses is the label key to identify the number of passes made for this simulation group.
	LabelSimulationGroupNumPasses = "sa.gardener.cloud/simulation-group-num-passes"
	// LabelTotalSimulations is the label key to identify the total number of simulations across all simulation groups at the time the group run result was produced.
	LabelTotalSimulations = "sa.gardener.cloud/total-simulations"
	// LabelNodePoolName is the label key to identify the node pool name for which the simulation is being run.
	LabelNodePoolName = "sa.gardener.cloud/node-pool-name"
	// LabelNodeTemplateName is the label key to identify the node template name for which the simulation is being run.
	LabelNodeTemplateName = "sa.gardener.cloud/node-template-name"
	// LabelRequestID is the label key to identify the request Name of scaling advice request.
	LabelRequestID = "sa.gardener.cloud/request-id"
	// LabelCorrelationID is the label key to identify the correlation Name of the scaling advice request.
	LabelCorrelationID = "sa.gardener.cloud/correlation-id"
)

const (
	// DefaultOperatorServerPort is the default port for the scaling advisor operator server.
	DefaultOperatorServerPort = 8080
	// DefaultOperatorHealthProbePort is the default port for the operator health probe endpoints.
	DefaultOperatorHealthProbePort = 8081
	// DefaultOperatorMetricsPort is the default port for the operator metrics endpoint.
	DefaultOperatorMetricsPort = 8082
	// DefaultOperatorProfilingPort is the default port for the operator profiling endpoints.
	DefaultOperatorProfilingPort = 8083
	// DefaultAdvisorServicePort is the default port for the scaling advisor core.
	DefaultAdvisorServicePort = 8090
	// DefaultMinKAPIPort is the default port for the MinKAPI core.
	DefaultMinKAPIPort = 8091
)

var (
	// DefaultMinKAPIBindAddress is the default bind address for the MinKAPI server.
	DefaultMinKAPIBindAddress = net.JoinHostPort("", strconv.Itoa(DefaultMinKAPIPort))
)

// ContextKey is the type alias for scaling advisor related context keys
type ContextKey string

const (
	// VerbosityCtxKey is the context key indicating the diagnostic/log verbosity.
	VerbosityCtxKey ContextKey = "verbosity"

	// TraceLogPathCtxKey is the context key under which the path to the trace log file is stored.
	TraceLogPathCtxKey ContextKey = "traceLogPath"
)
