//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and Gardener contributors
//
// SPDX-License-Identifier: Apache-2.0
// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackoffPolicy) DeepCopyInto(out *BackoffPolicy) {
	*out = *in
	out.InitialBackoffDuration = in.InitialBackoffDuration
	out.MaxBackoffDuration = in.MaxBackoffDuration
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackoffPolicy.
func (in *BackoffPolicy) DeepCopy() *BackoffPolicy {
	if in == nil {
		return nil
	}
	out := new(BackoffPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterScalingAdvice) DeepCopyInto(out *ClusterScalingAdvice) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterScalingAdvice.
func (in *ClusterScalingAdvice) DeepCopy() *ClusterScalingAdvice {
	if in == nil {
		return nil
	}
	out := new(ClusterScalingAdvice)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterScalingAdvice) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterScalingAdviceList) DeepCopyInto(out *ClusterScalingAdviceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterScalingAdvice, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterScalingAdviceList.
func (in *ClusterScalingAdviceList) DeepCopy() *ClusterScalingAdviceList {
	if in == nil {
		return nil
	}
	out := new(ClusterScalingAdviceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterScalingAdviceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterScalingAdviceSpec) DeepCopyInto(out *ClusterScalingAdviceSpec) {
	*out = *in
	if in.ScaleOutPlan != nil {
		in, out := &in.ScaleOutPlan, &out.ScaleOutPlan
		*out = new(ScaleOutPlan)
		(*in).DeepCopyInto(*out)
	}
	if in.ScaleInPlan != nil {
		in, out := &in.ScaleInPlan, &out.ScaleInPlan
		*out = new(ScaleInPlan)
		(*in).DeepCopyInto(*out)
	}
	out.ConstraintRef = in.ConstraintRef
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterScalingAdviceSpec.
func (in *ClusterScalingAdviceSpec) DeepCopy() *ClusterScalingAdviceSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterScalingAdviceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterScalingAdviceStatus) DeepCopyInto(out *ClusterScalingAdviceStatus) {
	*out = *in
	if in.Diagnostic != nil {
		in, out := &in.Diagnostic, &out.Diagnostic
		*out = new(ScalingAdviceDiagnostic)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterScalingAdviceStatus.
func (in *ClusterScalingAdviceStatus) DeepCopy() *ClusterScalingAdviceStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterScalingAdviceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstancePricing) DeepCopyInto(out *InstancePricing) {
	*out = *in
	if in.UnitCPUPrice != nil {
		in, out := &in.UnitCPUPrice, &out.UnitCPUPrice
		*out = new(float64)
		**out = **in
	}
	if in.UnitMemoryPrice != nil {
		in, out := &in.UnitMemoryPrice, &out.UnitMemoryPrice
		*out = new(float64)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstancePricing.
func (in *InstancePricing) DeepCopy() *InstancePricing {
	if in == nil {
		return nil
	}
	out := new(InstancePricing)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodePlacement) DeepCopyInto(out *NodePlacement) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodePlacement.
func (in *NodePlacement) DeepCopy() *NodePlacement {
	if in == nil {
		return nil
	}
	out := new(NodePlacement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodePool) DeepCopyInto(out *NodePool) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Quota != nil {
		in, out := &in.Quota, &out.Quota
		*out = make(corev1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
	if in.ScaleInPolicy != nil {
		in, out := &in.ScaleInPolicy, &out.ScaleInPolicy
		*out = new(ScaleInPolicy)
		**out = **in
	}
	if in.BackoffPolicy != nil {
		in, out := &in.BackoffPolicy, &out.BackoffPolicy
		*out = new(BackoffPolicy)
		**out = **in
	}
	if in.Taints != nil {
		in, out := &in.Taints, &out.Taints
		*out = make([]corev1.Taint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AvailabilityZones != nil {
		in, out := &in.AvailabilityZones, &out.AvailabilityZones
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.NodeTemplates != nil {
		in, out := &in.NodeTemplates, &out.NodeTemplates
		*out = make([]NodeTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodePool.
func (in *NodePool) DeepCopy() *NodePool {
	if in == nil {
		return nil
	}
	out := new(NodePool)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeTemplate) DeepCopyInto(out *NodeTemplate) {
	*out = *in
	if in.Capacity != nil {
		in, out := &in.Capacity, &out.Capacity
		*out = make(corev1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
	if in.KubeReserved != nil {
		in, out := &in.KubeReserved, &out.KubeReserved
		*out = make(corev1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
	if in.SystemReserved != nil {
		in, out := &in.SystemReserved, &out.SystemReserved
		*out = make(corev1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeTemplate.
func (in *NodeTemplate) DeepCopy() *NodeTemplate {
	if in == nil {
		return nil
	}
	out := new(NodeTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScaleInErrorInfo) DeepCopyInto(out *ScaleInErrorInfo) {
	*out = *in
	if in.NodeNames != nil {
		in, out := &in.NodeNames, &out.NodeNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScaleInErrorInfo.
func (in *ScaleInErrorInfo) DeepCopy() *ScaleInErrorInfo {
	if in == nil {
		return nil
	}
	out := new(ScaleInErrorInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScaleInItem) DeepCopyInto(out *ScaleInItem) {
	*out = *in
	out.NodePlacement = in.NodePlacement
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScaleInItem.
func (in *ScaleInItem) DeepCopy() *ScaleInItem {
	if in == nil {
		return nil
	}
	out := new(ScaleInItem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScaleInPlan) DeepCopyInto(out *ScaleInPlan) {
	*out = *in
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ScaleInItem, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScaleInPlan.
func (in *ScaleInPlan) DeepCopy() *ScaleInPlan {
	if in == nil {
		return nil
	}
	out := new(ScaleInPlan)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScaleInPolicy) DeepCopyInto(out *ScaleInPolicy) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScaleInPolicy.
func (in *ScaleInPolicy) DeepCopy() *ScaleInPolicy {
	if in == nil {
		return nil
	}
	out := new(ScaleInPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScaleOutErrorInfo) DeepCopyInto(out *ScaleOutErrorInfo) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScaleOutErrorInfo.
func (in *ScaleOutErrorInfo) DeepCopy() *ScaleOutErrorInfo {
	if in == nil {
		return nil
	}
	out := new(ScaleOutErrorInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScaleOutItem) DeepCopyInto(out *ScaleOutItem) {
	*out = *in
	out.NodePlacement = in.NodePlacement
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScaleOutItem.
func (in *ScaleOutItem) DeepCopy() *ScaleOutItem {
	if in == nil {
		return nil
	}
	out := new(ScaleOutItem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScaleOutPlan) DeepCopyInto(out *ScaleOutPlan) {
	*out = *in
	if in.UnsatisfiedPodNames != nil {
		in, out := &in.UnsatisfiedPodNames, &out.UnsatisfiedPodNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ScaleOutItem, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScaleOutPlan.
func (in *ScaleOutPlan) DeepCopy() *ScaleOutPlan {
	if in == nil {
		return nil
	}
	out := new(ScaleOutPlan)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScalingAdviceDiagnostic) DeepCopyInto(out *ScalingAdviceDiagnostic) {
	*out = *in
	if in.SimRunResults != nil {
		in, out := &in.SimRunResults, &out.SimRunResults
		*out = make([]ScalingSimRunResult, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScalingAdviceDiagnostic.
func (in *ScalingAdviceDiagnostic) DeepCopy() *ScalingAdviceDiagnostic {
	if in == nil {
		return nil
	}
	out := new(ScalingAdviceDiagnostic)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScalingConstraint) DeepCopyInto(out *ScalingConstraint) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScalingConstraint.
func (in *ScalingConstraint) DeepCopy() *ScalingConstraint {
	if in == nil {
		return nil
	}
	out := new(ScalingConstraint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ScalingConstraint) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScalingConstraintList) DeepCopyInto(out *ScalingConstraintList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ScalingConstraint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScalingConstraintList.
func (in *ScalingConstraintList) DeepCopy() *ScalingConstraintList {
	if in == nil {
		return nil
	}
	out := new(ScalingConstraintList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ScalingConstraintList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScalingConstraintSpec) DeepCopyInto(out *ScalingConstraintSpec) {
	*out = *in
	if in.DefaultBackoffPolicy != nil {
		in, out := &in.DefaultBackoffPolicy, &out.DefaultBackoffPolicy
		*out = new(BackoffPolicy)
		**out = **in
	}
	if in.ScaleInPolicy != nil {
		in, out := &in.ScaleInPolicy, &out.ScaleInPolicy
		*out = new(ScaleInPolicy)
		**out = **in
	}
	if in.NodePools != nil {
		in, out := &in.NodePools, &out.NodePools
		*out = make([]NodePool, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScalingConstraintSpec.
func (in *ScalingConstraintSpec) DeepCopy() *ScalingConstraintSpec {
	if in == nil {
		return nil
	}
	out := new(ScalingConstraintSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScalingConstraintStatus) DeepCopyInto(out *ScalingConstraintStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScalingConstraintStatus.
func (in *ScalingConstraintStatus) DeepCopy() *ScalingConstraintStatus {
	if in == nil {
		return nil
	}
	out := new(ScalingConstraintStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScalingFeedback) DeepCopyInto(out *ScalingFeedback) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScalingFeedback.
func (in *ScalingFeedback) DeepCopy() *ScalingFeedback {
	if in == nil {
		return nil
	}
	out := new(ScalingFeedback)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ScalingFeedback) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScalingFeedbackList) DeepCopyInto(out *ScalingFeedbackList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ScalingFeedback, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScalingFeedbackList.
func (in *ScalingFeedbackList) DeepCopy() *ScalingFeedbackList {
	if in == nil {
		return nil
	}
	out := new(ScalingFeedbackList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ScalingFeedbackList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScalingFeedbackSpec) DeepCopyInto(out *ScalingFeedbackSpec) {
	*out = *in
	out.ConstraintRef = in.ConstraintRef
	if in.ScaleOutErrorInfos != nil {
		in, out := &in.ScaleOutErrorInfos, &out.ScaleOutErrorInfos
		*out = make([]ScaleOutErrorInfo, len(*in))
		copy(*out, *in)
	}
	in.ScaleInErrorInfo.DeepCopyInto(&out.ScaleInErrorInfo)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScalingFeedbackSpec.
func (in *ScalingFeedbackSpec) DeepCopy() *ScalingFeedbackSpec {
	if in == nil {
		return nil
	}
	out := new(ScalingFeedbackSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScalingSimRunResult) DeepCopyInto(out *ScalingSimRunResult) {
	*out = *in
	if in.ScheduledPodNames != nil {
		in, out := &in.ScheduledPodNames, &out.ScheduledPodNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScalingSimRunResult.
func (in *ScalingSimRunResult) DeepCopy() *ScalingSimRunResult {
	if in == nil {
		return nil
	}
	out := new(ScalingSimRunResult)
	in.DeepCopyInto(out)
	return out
}
